In [739]:
import pandas as pd
df=pd.read_csv('augmented_survey.csv', na_values='?').dropna()
df

,Q1. What is your gender?,Q2. What is your approximate monthly allowance / pocket money?,Q3. Which year of college are you in?,Q4. What type of venue did you go to?,Q5. What day was the outing?,Q6. Who initiated / planned the outing?,Q7. What was the occasion?,"Q8. How many people were in your group, including yourself?",Q9. How far did you travel to reach the venue?,"Q10. Approximately how much did YOU personally spend on this outing? (₹) (Include food, travel, entry, shopping — everything)",Q11. Did you have a rough budget in mind before going?,Q12. Did your actual spending exceed that budget? (Answer only if Q11 = Yes),Q13. What was the biggest reason you spent what you did? (Pick one),Q14. How often do you go on social outings per month?,"Q15. On a scale of 1–5, how much do your friends' choices influence where you go and what you spend? (1 = Not at all, 5 = Completely driven by friends)","Q16. Did you use any discount or offer? (Zomato, Swiggy Dineout, student discount, etc.)"
0,Female,"Less than ₹3,000",2nd Year,Café / Coffee Shop,Weekday (Mon–Thu),A friend did,Just hanging out (no specific reason),3–4 people,Less than 2 km,₹200 – ₹500,No,"Yes, I spent more than I planned",I was in a good mood,2–3 times,4,No
1,Female,"₹10,001 – ₹15,000",2nd Year,Movie Theatre,Weekday (Mon–Thu),I did,Just hanging out (no specific reason),5–7 people,2–5 km,"₹501 – ₹1,000",Yes,"Yes, I spent more than I planned",I was in a good mood,4–5 times,3,Yes
2,Female,"₹3,000 – ₹6,000",2nd Year,Café / Coffee Shop,Weekend (Sat–Sun),It was a group decision,Just hanging out (no specific reason),5–7 people,6–10 km,"₹501 – ₹1,000",Yes,"No, I stayed within my budget",The venue/place itself was expensive,2–3 times,3,No
3,Male,"₹6,001 – ₹10,000",1st Year,Pub / Bar / Lounge,Weekday (Mon–Thu),I did,After exams / stress relief,2 people,Less than 2 km,"₹501 – ₹1,000",Yes,"No, I stayed within my budget",I just didn't track / wasn't paying attention,2–3 times,3,No
4,Male,"₹3,000 – ₹6,000",1st Year,Park / Outdoor space,Weekday (Mon–Thu),"It was spontaneous, no one planned it",Just hanging out (no specific reason),3–4 people,2–5 km,Less than ₹200,No,"No, I stayed within my budget",I just didn't track / wasn't paying attention,More than 5 times,4,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
415,Male,"₹6,001 – ₹10,000",1st Year,Park / Outdoor space,Weekend (Sat–Sun),"It was spontaneous, no one planned it",Date / romantic outing,5–7 people,Less than 2 km,₹200 – ₹500,No,"Yes, I spent more than I planned",I was in a good mood,4–5 times,2,Yes
416,Female,"₹6,001 – ₹10,000",2nd Year,Pub / Bar / Lounge,Weekend (Sat–Sun),It was a group decision,"Celebration (birthday, farewell, etc.)",3–4 people,More than 10 km,"₹1,001 – ₹2,000",Yes,"No, I stayed within my budget",The venue/place itself was expensive,2–3 times,2,No
417,Male,"More than ₹15,000",2nd Year,Café / Coffee Shop,Weekend (Sat–Sun),I did,Just hanging out (no specific reason),8 or more,Less than 2 km,"₹501 – ₹1,000",No,"No, I stayed within my budget",I just didn't track / wasn't paying attention,More than 5 times,2,No
418,Male,"₹3,000 – ₹6,000",2nd Year,Pub / Bar / Lounge,Weekend (Sat–Sun),"It was spontaneous, no one planned it",Just hanging out (no specific reason),2 people,2–5 km,"₹501 – ₹1,000",Yes,I spent exactly what I planned,I was trying to save / was on a budget,Once or less,2,No
419,Male,"Less than ₹3,000",2nd Year,Park / Outdoor space,Weekend (Sat–Sun),A friend did,Just hanging out (no specific reason),3–4 people,2–5 km,Less than ₹200,No,No budget,I was in a good mood,Once or less,4,No

In [740]:
df = pd.read_excel('augmented_survey.xlsx')

df['gender']         = df['Q1. What is your gender?']
df['allowance']      = df['Q2. What is your approximate monthly allowance / pocket money?']
df['year']           = df['Q3. Which year of college are you in?']
df['venue']          = df['Q4. What type of venue did you go to?']
df['day']            = df['Q5. What day was the outing?']
df['intiated_plan']  = df['Q6. Who initiated / planned the outing?']
df['occasion']       = df['Q7. What was the occasion?']
df['group_size']     = df['Q8. How many people were in your group, including yourself?']
df['travel_dist']    = df['Q9. How far did you travel to reach the venue?']
df['spending']       = df['Q10. Approximately how much did YOU personally spend on this outing? (₹) (Include food, travel, entry, shopping — everything)']
df['rough_budget']   = df['Q11. Did you have a rough budget in mind before going?']
df['exceed_budget']  = df['Q12. Did your actual spending exceed that budget? (Answer only if Q11 = Yes)']
df['spend_reason']   = df['Q13. What was the biggest reason you spent what you did? (Pick one)']
df['outing_freq']    = df['Q14. How often do you go on social outings per month?']
df['peer_influence'] = df["Q15. On a scale of 1–5, how much do your friends' choices influence where you go and what you spend? (1 = Not at all, 5 = Completely driven by friends)"]
df['discount']       = df['Q16. Did you use any discount or offer? (Zomato, Swiggy Dineout, student discount, etc.)']

df = df.drop(columns={'Q1. What is your gender?',
       'Q2. What is your approximate monthly allowance / pocket money?',
       'Q3. Which year of college are you in?',
       'Q4. What type of venue did you go to?', 'Q5. What day was the outing?',
       'Q6. Who initiated / planned the outing?', 'Q7. What was the occasion?',
       'Q8. How many people were in your group, including yourself?',
       'Q9. How far did you travel to reach the venue?',
       'Q10. Approximately how much did YOU personally spend on this outing? (₹) (Include food, travel, entry, shopping — everything)',
       'Q11. Did you have a rough budget in mind before going?',
       'Q12. Did your actual spending exceed that budget? (Answer only if Q11 = Yes)',
       'Q13. What was the biggest reason you spent what you did? (Pick one)',
       'Q14. How often do you go on social outings per month?',
       "Q15. On a scale of 1–5, how much do your friends' choices influence where you go and what you spend? (1 = Not at all, 5 = Completely driven by friends)",
       'Q16. Did you use any discount or offer? (Zomato, Swiggy Dineout, student discount, etc.)'})
df

,gender,allowance,year,venue,day,intiated_plan,occasion,group_size,travel_dist,spending,rough_budget,exceed_budget,spend_reason,outing_freq,peer_influence,discount
0,Female,"Less than ₹3,000",2nd Year,Café / Coffee Shop,Weekday (Mon–Thu),A friend did,Just hanging out (no specific reason),3–4 people,Less than 2 km,₹200 – ₹500,No,"Yes, I spent more than I planned",I was in a good mood,2–3 times,4,No
1,Female,"₹10,001 – ₹15,000",2nd Year,Movie Theatre,Weekday (Mon–Thu),I did,Just hanging out (no specific reason),5–7 people,2–5 km,"₹501 – ₹1,000",Yes,"Yes, I spent more than I planned",I was in a good mood,4–5 times,3,Yes
2,Female,"₹3,000 – ₹6,000",2nd Year,Café / Coffee Shop,Weekend (Sat–Sun),It was a group decision,Just hanging out (no specific reason),5–7 people,6–10 km,"₹501 – ₹1,000",Yes,"No, I stayed within my budget",The venue/place itself was expensive,2–3 times,3,No
3,Male,"₹6,001 – ₹10,000",1st Year,Pub / Bar / Lounge,Weekday (Mon–Thu),I did,After exams / stress relief,2 people,Less than 2 km,"₹501 – ₹1,000",Yes,"No, I stayed within my budget",I just didn't track / wasn't paying attention,2–3 times,3,No
4,Male,"₹3,000 – ₹6,000",1st Year,Park / Outdoor space,Weekday (Mon–Thu),"It was spontaneous, no one planned it",Just hanging out (no specific reason),3–4 people,2–5 km,Less than ₹200,No,"No, I stayed within my budget",I just didn't track / wasn't paying attention,More than 5 times,4,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
415,Male,"₹6,001 – ₹10,000",1st Year,Park / Outdoor space,Weekend (Sat–Sun),"It was spontaneous, no one planned it",Date / romantic outing,5–7 people,Less than 2 km,₹200 – ₹500,No,"Yes, I spent more than I planned",I was in a good mood,4–5 times,2,Yes
416,Female,"₹6,001 – ₹10,000",2nd Year,Pub / Bar / Lounge,Weekend (Sat–Sun),It was a group decision,"Celebration (birthday, farewell, etc.)",3–4 people,More than 10 km,"₹1,001 – ₹2,000",Yes,"No, I stayed within my budget",The venue/place itself was expensive,2–3 times,2,No
417,Male,"More than ₹15,000",2nd Year,Café / Coffee Shop,Weekend (Sat–Sun),I did,Just hanging out (no specific reason),8 or more,Less than 2 km,"₹501 – ₹1,000",No,"No, I stayed within my budget",I just didn't track / wasn't paying attention,More than 5 times,2,No
418,Male,"₹3,000 – ₹6,000",2nd Year,Pub / Bar / Lounge,Weekend (Sat–Sun),"It was spontaneous, no one planned it",Just hanging out (no specific reason),2 people,2–5 km,"₹501 – ₹1,000",Yes,I spent exactly what I planned,I was trying to save / was on a budget,Once or less,2,No
419,Male,"Less than ₹3,000",2nd Year,Park / Outdoor space,Weekend (Sat–Sun),A friend did,Just hanging out (no specific reason),3–4 people,2–5 km,Less than ₹200,No,No budget,I was in a good mood,Once or less,4,No

In [741]:
allowance_map = {
    'Less than ₹3,000': 1500,
    '₹3,000 – ₹6,000': 4500,
    '₹6,001 – ₹10,000': 8000,
    '₹10,001 – ₹15,000': 12500,
    'More than ₹15,000': 18000
}

spending_map = {
    'Less than ₹200': 100,
    '₹200 – ₹500': 350,
    '₹501 – ₹1,000': 750,
    '₹1,001 – ₹2,000': 1500,
    'More than ₹2,000': 2500
}

df['allowance'] = df['allowance'].map(allowance_map)
df['spending'] = df['spending'].map(spending_map)

In [742]:
df.nunique()

gender            2
allowance         5
year              4
venue             7
day               3
intiated_plan     4
occasion          5
group_size        4
travel_dist       4
spending          5
rough_budget      2
exceed_budget     4
spend_reason      6
outing_freq       4
peer_influence    5
discount          2
dtype: int64

In [743]:
df= df.iloc[:140]
df

,gender,allowance,year,venue,day,intiated_plan,occasion,group_size,travel_dist,spending,rough_budget,exceed_budget,spend_reason,outing_freq,peer_influence,discount
0,Female,1500,2nd Year,Café / Coffee Shop,Weekday (Mon–Thu),A friend did,Just hanging out (no specific reason),3–4 people,Less than 2 km,350,No,"Yes, I spent more than I planned",I was in a good mood,2–3 times,4,No
1,Female,12500,2nd Year,Movie Theatre,Weekday (Mon–Thu),I did,Just hanging out (no specific reason),5–7 people,2–5 km,750,Yes,"Yes, I spent more than I planned",I was in a good mood,4–5 times,3,Yes
2,Female,4500,2nd Year,Café / Coffee Shop,Weekend (Sat–Sun),It was a group decision,Just hanging out (no specific reason),5–7 people,6–10 km,750,Yes,"No, I stayed within my budget",The venue/place itself was expensive,2–3 times,3,No
3,Male,8000,1st Year,Pub / Bar / Lounge,Weekday (Mon–Thu),I did,After exams / stress relief,2 people,Less than 2 km,750,Yes,"No, I stayed within my budget",I just didn't track / wasn't paying attention,2–3 times,3,No
4,Male,4500,1st Year,Park / Outdoor space,Weekday (Mon–Thu),"It was spontaneous, no one planned it",Just hanging out (no specific reason),3–4 people,2–5 km,100,No,"No, I stayed within my budget",I just didn't track / wasn't paying attention,More than 5 times,4,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,Male,8000,2nd Year,Movie Theatre,Weekend (Sat–Sun),A friend did,Just hanging out (no specific reason),2 people,Less than 2 km,100,Yes,"No, I stayed within my budget",The venue/place itself was expensive,2–3 times,5,Yes
136,Male,8000,2nd Year,Café / Coffee Shop,Weekend (Sat–Sun),"It was spontaneous, no one planned it",Just hanging out (no specific reason),5–7 people,6–10 km,350,No,"No, I stayed within my budget",The venue/place itself was expensive,Once or less,4,Yes
137,Male,4500,1st Year,Café / Coffee Shop,Weekend (Sat–Sun),It was a group decision,Other,3–4 people,6–10 km,350,No,"No, I stayed within my budget",The venue/place itself was expensive,2–3 times,3,Yes
138,Male,1500,2nd Year,Café / Coffee Shop,Weekend (Sat–Sun),"It was spontaneous, no one planned it",Just hanging out (no specific reason),5–7 people,6–10 km,350,Yes,I spent exactly what I planned,It was a special occasion so I didn't hold back,4–5 times,3,No
139,Female,18000,2nd Year,Café / Coffee Shop,Weekday (Mon–Thu),A friend did,Just hanging out (no specific reason),5–7 people,2–5 km,750,No,"Yes, I spent more than I planned",The venue/place itself was expensive,More than 5 times,2,Yes

In [744]:
# 1. Apply One-Hot Encoding
# This converts text categories into separate numeric columns (0 and 1)
df = pd.get_dummies(df, columns=[
    'group_size','peer_influence', 'gender', 'venue', 'day', 'intiated_plan', 'occasion',
    'exceed_budget', 'spend_reason', 'rough_budget', 'discount',
    'travel_dist', 'outing_freq' ,'year'
])
df.columns

Index(['allowance', 'spending', 'group_size_2 people', 'group_size_3–4 people',
       'group_size_5–7 people', 'group_size_8 or more', 'peer_influence_1',
       'peer_influence_2', 'peer_influence_3', 'peer_influence_4',
       'peer_influence_5', 'gender_Female', 'gender_Male',
       'venue_Café / Coffee Shop', 'venue_Mall / Shopping',
       'venue_Movie Theatre', 'venue_Other', 'venue_Park / Outdoor space',
       'venue_Pub / Bar / Lounge', 'venue_Restaurant / Dhaba', 'day_Friday',
       'day_Weekday (Mon–Thu)', 'day_Weekend (Sat–Sun)',
       'intiated_plan_A friend did', 'intiated_plan_I did',
       'intiated_plan_It was a group decision',
       'intiated_plan_It was spontaneous, no one planned it',
       'occasion_After exams / stress relief',
       'occasion_Celebration (birthday, farewell, etc.)',
       'occasion_Date / romantic outing',
       'occasion_Just hanging out (no specific reason)', 'occasion_Other',
       'exceed_budget_I spent exactly what I planned',
       'exceed_budget_No budget',
       'exceed_budget_No, I stayed within my budget',
       'exceed_budget_Yes, I spent more than I planned',
       'spend_reason_I just didn't track / wasn't paying attention',
       'spend_reason_I was in a good mood',
       'spend_reason_I was trying to save / was on a budget',
       'spend_reason_It was a special occasion so I didn't hold back',
       'spend_reason_My friends were spending so I did too (peer influence)',
       'spend_reason_The venue/place itself was expensive', 'rough_budget_No',
       'rough_budget_Yes', 'discount_No', 'discount_Yes', 'travel_dist_2–5 km',
       'travel_dist_6–10 km', 'travel_dist_Less than 2 km',
       'travel_dist_More than 10 km', 'outing_freq_2–3 times',
       'outing_freq_4–5 times', 'outing_freq_More than 5 times',
       'outing_freq_Once or less', 'year_1st Year', 'year_2nd Year',
       'year_3rd Year', 'year_4th Year / Final Year'],
      dtype='object')

In [745]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140 entries, 0 to 139
Data columns (total 58 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   allowance                                                            140 non-null    int64
 1   spending                                                             140 non-null    int64
 2   group_size_2 people                                                  140 non-null    bool
 3   group_size_3–4 people                                                140 non-null    bool
 4   group_size_5–7 people                                                140 non-null    bool
 5   group_size_8 or more                                                 140 non-null    bool
 6   peer_influence_1                                                     140 non-null    bool
 7   peer_influence_2                                                     140 non-null    bool
 8   peer_influence_3                                                     140 non-null    bool
 9   peer_influence_4                                                     140 non-null    bool
 10  peer_influence_5                                                     140 non-null    bool
 11  gender_Female                                                        140 non-null    bool
 12  gender_Male                                                          140 non-null    bool
 13  venue_Café / Coffee Shop                                             140 non-null    bool
 14  venue_Mall / Shopping                                                140 non-null    bool
 15  venue_Movie Theatre                                                  140 non-null    bool
 16  venue_Other                                                          140 non-null    bool
 17  venue_Park / Outdoor space                                           140 non-null    bool
 18  venue_Pub / Bar / Lounge                                             140 non-null    bool
 19  venue_Restaurant / Dhaba                                             140 non-null    bool
 20  day_Friday                                                           140 non-null    bool
 21  day_Weekday (Mon–Thu)                                                140 non-null    bool
 22  day_Weekend (Sat–Sun)                                                140 non-null    bool
 23  intiated_plan_A friend did                                           140 non-null    bool
 24  intiated_plan_I did                                                  140 non-null    bool
 25  intiated_plan_It was a group decision                                140 non-null    bool
 26  intiated_plan_It was spontaneous, no one planned it                  140 non-null    bool
 27  occasion_After exams / stress relief                                 140 non-null    bool
 28  occasion_Celebration (birthday, farewell, etc.)                      140 non-null    bool
 29  occasion_Date / romantic outing                                      140 non-null    bool
 30  occasion_Just hanging out (no specific reason)                       140 non-null    bool
 31  occasion_Other                                                       140 non-null    bool
 32  exceed_budget_I spent exactly what I planned                         140 non-null    bool
 33  exceed_budget_No budget                                              140 non-null    bool
 34  exceed_budget_No, I stayed within my budget                          140 non-null    bool
 35  exceed_budget_Yes, I spent more than I planned                       140 non-null    bool
 36  spend_reason_I just didn't track / wasn't paying attention           140 non-null    bool
 37  spend_reason_I was in a good mood                                    140 non-null    bool
 38  spend_reason_I was trying to save / was on a budget                  140 non-null    bool
 39  spend_reason_It was a special occasion so I didn't hold back         140 non-null    bool
 40  spend_reason_My friends were spending so I did too (peer influence)  140 non-null    bool
 41  spend_reason_The venue/place itself was expensive                    140 non-null    bool
 42  rough_budget_No                                                      140 non-null    bool
 43  rough_budget_Yes                                                     140 non-null    bool
 44  discount_No                                                          140 non-null    bool
 45  discount_Yes                                                         140 non-null    bool
 46  travel_dist_2–5 km                                                   140 non-null    bool
 47  travel_dist_6–10 km                                                  140 non-null    bool
 48  travel_dist_Less than 2 km                                           140 non-null    bool
 49  travel_dist_More than 10 km                                          140 non-null    bool
 50  outing_freq_2–3 times                                                140 non-null    bool
 51  outing_freq_4–5 times                                                140 non-null    bool
 52  outing_freq_More than 5 times                                        140 non-null    bool
 53  outing_freq_Once or less                                             140 non-null    bool
 54  year_1st Year                                                        140 non-null    bool
 55  year_2nd Year                                                        140 non-null    bool
 56  year_3rd Year                                                        140 non-null    bool
 57  year_4th Year / Final Year                                           140 non-null    bool
dtypes: bool(56), int64(2)
memory usage: 10.0 KB

In [746]:
from sklearn.preprocessing import StandardScaler

# 1. Separate Target (Y)
Y = df['spending']

X = df[['allowance', 'group_size_2 people', 'group_size_3–4 people',
    'group_size_5–7 people', 'group_size_8 or more', 'peer_influence_1',
    'peer_influence_2', 'peer_influence_3', 'peer_influence_4',
    'peer_influence_5', 'gender_Female', 'gender_Male',
    'venue_Café / Coffee Shop', 'venue_Mall / Shopping',
    'venue_Movie Theatre', 'venue_Other', 'venue_Park / Outdoor space',
    'venue_Pub / Bar / Lounge', 'venue_Restaurant / Dhaba', 'day_Friday',
    'day_Weekday (Mon–Thu)', 'day_Weekend (Sat–Sun)',
    'intiated_plan_A friend did', 'intiated_plan_I did',
    'intiated_plan_It was a group decision',
    'intiated_plan_It was spontaneous, no one planned it',
    'occasion_After exams / stress relief',
    'occasion_Celebration (birthday, farewell, etc.)',
    'occasion_Date / romantic outing',
    'occasion_Just hanging out (no specific reason)', 'occasion_Other',
    'exceed_budget_I spent exactly what I planned',
    'exceed_budget_No budget',
    'exceed_budget_No, I stayed within my budget',
    'exceed_budget_Yes, I spent more than I planned',
    "spend_reason_I just didn't track / wasn't paying attention",  # ← double quotes
    'spend_reason_I was in a good mood',
    'spend_reason_I was trying to save / was on a budget',
    "spend_reason_It was a special occasion so I didn't hold back",  # ← double quotes
    'spend_reason_My friends were spending so I did too (peer influence)',
    'spend_reason_The venue/place itself was expensive', 'rough_budget_No',
    'rough_budget_Yes', 'discount_No', 'discount_Yes', 'travel_dist_2–5 km',
    'travel_dist_6–10 km', 'travel_dist_Less than 2 km',
    'travel_dist_More than 10 km', 'outing_freq_2–3 times',
    'outing_freq_4–5 times', 'outing_freq_More than 5 times',
    'outing_freq_Once or less', 'year_1st Year', 'year_2nd Year',
    'year_3rd Year', 'year_4th Year / Final Year'
]]

scaler = StandardScaler()
X_scaled_array = scaler.fit_transform(X_raw)

# 4. Final X for your Lasso/Ridge
X = pd.DataFrame(X_scaled_array, columns=X_raw.columns)

In [747]:
df.columns

Index(['allowance', 'spending', 'group_size_2 people', 'group_size_3–4 people',
       'group_size_5–7 people', 'group_size_8 or more', 'peer_influence_1',
       'peer_influence_2', 'peer_influence_3', 'peer_influence_4',
       'peer_influence_5', 'gender_Female', 'gender_Male',
       'venue_Café / Coffee Shop', 'venue_Mall / Shopping',
       'venue_Movie Theatre', 'venue_Other', 'venue_Park / Outdoor space',
       'venue_Pub / Bar / Lounge', 'venue_Restaurant / Dhaba', 'day_Friday',
       'day_Weekday (Mon–Thu)', 'day_Weekend (Sat–Sun)',
       'intiated_plan_A friend did', 'intiated_plan_I did',
       'intiated_plan_It was a group decision',
       'intiated_plan_It was spontaneous, no one planned it',
       'occasion_After exams / stress relief',
       'occasion_Celebration (birthday, farewell, etc.)',
       'occasion_Date / romantic outing',
       'occasion_Just hanging out (no specific reason)', 'occasion_Other',
       'exceed_budget_I spent exactly what I planned',
       'exceed_budget_No budget',
       'exceed_budget_No, I stayed within my budget',
       'exceed_budget_Yes, I spent more than I planned',
       'spend_reason_I just didn't track / wasn't paying attention',
       'spend_reason_I was in a good mood',
       'spend_reason_I was trying to save / was on a budget',
       'spend_reason_It was a special occasion so I didn't hold back',
       'spend_reason_My friends were spending so I did too (peer influence)',
       'spend_reason_The venue/place itself was expensive', 'rough_budget_No',
       'rough_budget_Yes', 'discount_No', 'discount_Yes', 'travel_dist_2–5 km',
       'travel_dist_6–10 km', 'travel_dist_Less than 2 km',
       'travel_dist_More than 10 km', 'outing_freq_2–3 times',
       'outing_freq_4–5 times', 'outing_freq_More than 5 times',
       'outing_freq_Once or less', 'year_1st Year', 'year_2nd Year',
       'year_3rd Year', 'year_4th Year / Final Year'],
      dtype='object')

In [748]:
#allowance, group_size, travel_dist,spending, outing_freq peer_influence

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import scale
import sklearn.linear_model as lm
import statsmodels.formula.api as smf
from statsmodels.stats.outliers_influence import variance_inflation_factor
import statsmodels.api as sm

from sklearn.preprocessing import scale
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import minmax_scale

In [749]:
# step 1 : preprocessing (drop removing any na value and special characters label encoding(too many) or one hot encoding (m/f), standard scaler excluding target variable ( here exclude medv) )
# step 2: check linearity only with the continous variable 
# step 3: check vif (drop vraibles whose vif is greater than 5)
# step 4: do ridge and lasso based on alpha(best)
# step 5: do linear regression drop the value whose p value is greater 0.05 
# step 5 or 6 : spilt train test or kfold cross validation (prefereed )
# step 6: do linear regression on the training datasets drop the value whose p value is greater 0.05 
# step : x and y in and then train test kfold 
# step 7: find out the mse for both training and testing 
# same procedure for logistic

# 70 reg 10 non parametric mle 20 hypothesis 20 anova manova 20 
# 42 marks theory out of 140

In [750]:

df['allowance2'] = df['allowance'] ** 2

In [751]:
import statsmodels.formula.api as smf

# --- 1. ALLOWANCE ---
print("="*30 + "\nANALYSIS: allowance\n" + "="*30)
print(smf.ols('spending ~ allowance', df).fit().summary())
print("\n--- ADDING SQUARED TERM ---")
print(smf.ols('spending ~ allowance + allowance2', df).fit().summary())

==============================
ANALYSIS: allowance
==============================
                            OLS Regression Results
==============================================================================
Dep. Variable:               spending   R-squared:                       0.028
Model:                            OLS   Adj. R-squared:                  0.021
Method:                 Least Squares   F-statistic:                     3.939
Date:                Wed, 22 Apr 2026   Prob (F-statistic):             0.0492
Time:                        18:30:58   Log-Likelihood:                -1105.5
No. Observations:                 140   AIC:                             2215.
Df Residuals:                     138   BIC:                             2221.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    702.8519     86.042      8.169      0.000     532.721     872.983
allowance      0.0218      0.011      1.985      0.049    8.23e-05       0.044
==============================================================================
Omnibus:                       24.143   Durbin-Watson:                   2.153
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               30.543
Skew:                           1.110   Prob(JB):                     2.33e-07
Kurtosis:                       3.558   Cond. No.                     1.22e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.22e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

--- ADDING SQUARED TERM ---
                            OLS Regression Results
==============================================================================
Dep. Variable:               spending   R-squared:                       0.028
Model:                            OLS   Adj. R-squared:                  0.014
Method:                 Least Squares   F-statistic:                     1.983
Date:                Wed, 22 Apr 2026   Prob (F-statistic):              0.142
Time:                        18:30:59   Log-Likelihood:                -1105.5
No. Observations:                 140   AIC:                             2217.
Df Residuals:                     137   BIC:                             2226.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    725.5171    130.920      5.542      0.000     466.631     984.403
allowance      0.0130      0.040      0.328      0.743      -0.066       0.092
allowance2  4.901e-07   2.13e-06      0.230      0.818   -3.72e-06     4.7e-06
==============================================================================
Omnibus:                       23.880   Durbin-Watson:                   2.149
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               30.091
Skew:                           1.101   Prob(JB):                     2.92e-07
Kurtosis:                       3.555   Cond. No.                     2.64e+08
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.64e+08. This might indicate that there are
strong multicollinearity or other numerical problems.

In [752]:
# Pass a list of strings and fix the 'travel' typo
df = df.drop(columns=['allowance2'])

In [753]:
df.columns

Index(['allowance', 'spending', 'group_size_2 people', 'group_size_3–4 people',
       'group_size_5–7 people', 'group_size_8 or more', 'peer_influence_1',
       'peer_influence_2', 'peer_influence_3', 'peer_influence_4',
       'peer_influence_5', 'gender_Female', 'gender_Male',
       'venue_Café / Coffee Shop', 'venue_Mall / Shopping',
       'venue_Movie Theatre', 'venue_Other', 'venue_Park / Outdoor space',
       'venue_Pub / Bar / Lounge', 'venue_Restaurant / Dhaba', 'day_Friday',
       'day_Weekday (Mon–Thu)', 'day_Weekend (Sat–Sun)',
       'intiated_plan_A friend did', 'intiated_plan_I did',
       'intiated_plan_It was a group decision',
       'intiated_plan_It was spontaneous, no one planned it',
       'occasion_After exams / stress relief',
       'occasion_Celebration (birthday, farewell, etc.)',
       'occasion_Date / romantic outing',
       'occasion_Just hanging out (no specific reason)', 'occasion_Other',
       'exceed_budget_I spent exactly what I planned',
       'exceed_budget_No budget',
       'exceed_budget_No, I stayed within my budget',
       'exceed_budget_Yes, I spent more than I planned',
       'spend_reason_I just didn't track / wasn't paying attention',
       'spend_reason_I was in a good mood',
       'spend_reason_I was trying to save / was on a budget',
       'spend_reason_It was a special occasion so I didn't hold back',
       'spend_reason_My friends were spending so I did too (peer influence)',
       'spend_reason_The venue/place itself was expensive', 'rough_budget_No',
       'rough_budget_Yes', 'discount_No', 'discount_Yes', 'travel_dist_2–5 km',
       'travel_dist_6–10 km', 'travel_dist_Less than 2 km',
       'travel_dist_More than 10 km', 'outing_freq_2–3 times',
       'outing_freq_4–5 times', 'outing_freq_More than 5 times',
       'outing_freq_Once or less', 'year_1st Year', 'year_2nd Year',
       'year_3rd Year', 'year_4th Year / Final Year'],
      dtype='object')

In [754]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.tools.tools import add_constant
X=df[["allowance"]] # maybe we need to take either stat or lstat2
X = add_constant(X)
#X = add_constant(df4)
#X = X.iloc[:,1:]
vif_df = pd.DataFrame()
vif_df["feature"] = X.columns

# calculating VIF for each feature
vif_df["VIF"] = [variance_inflation_factor(X.values, i)
                          for i in range(len(X.columns))]
 
#Print the dataframe with VIF values 
print(vif_df)

     feature      VIF
0      const  2.41497
1  allowance  1.00000

In [755]:
# step 1 : preprocessing (drop removing any na value and special characters label encoding(too many) or one hot encoding (m/f), standard scaler excluding target variable ( here exclude medv) )
# step 2: check linearity only with the continous variable 
# step 3: check vif (drop vraibles whose vif is greater than 5)
# step 4: do ridge and lasso based on alpha(best)
# step 5: do linear regression drop the value whose p value is greater 0.05 
# step 5 or 6 : spilt train test or kfold cross validation (prefereed )
# step 6: do linear regression on the training datasets drop the value whose p value is greater 0.05 
# step : x and y in and then train test kfold 
# step 7: find out the mse for both training and testing 
# same procedure for logistic

# 70 reg 10 non parametric mle 20 hypothesis 20 anova manova 20 
# 42 marks theory out of 140

In [756]:
Y = df['spending']

X = df[[
    'allowance', 'group_size_2 people', 'group_size_3–4 people',
    'group_size_5–7 people', 'group_size_8 or more', 'peer_influence_1',
    'peer_influence_2', 'peer_influence_3', 'peer_influence_4',
    'peer_influence_5', 'gender_Female', 'gender_Male',
    'venue_Café / Coffee Shop', 'venue_Mall / Shopping',
    'venue_Movie Theatre', 'venue_Other', 'venue_Park / Outdoor space',
    'venue_Pub / Bar / Lounge', 'venue_Restaurant / Dhaba', 'day_Friday',
    'day_Weekday (Mon–Thu)', 'day_Weekend (Sat–Sun)',
    'intiated_plan_A friend did', 'intiated_plan_I did',
    'intiated_plan_It was a group decision',
    'intiated_plan_It was spontaneous, no one planned it',
    'occasion_After exams / stress relief',
    'occasion_Celebration (birthday, farewell, etc.)',
    'occasion_Date / romantic outing',
    'occasion_Just hanging out (no specific reason)', 'occasion_Other',
    'exceed_budget_I spent exactly what I planned',
    'exceed_budget_No budget',
    'exceed_budget_No, I stayed within my budget',
    'exceed_budget_Yes, I spent more than I planned',
    "spend_reason_I just didn't track / wasn't paying attention",  # ← double quotes
    'spend_reason_I was in a good mood',
    'spend_reason_I was trying to save / was on a budget',
    "spend_reason_It was a special occasion so I didn't hold back",  # ← double quotes
    'spend_reason_My friends were spending so I did too (peer influence)',
    'spend_reason_The venue/place itself was expensive', 'rough_budget_No',
    'rough_budget_Yes', 'discount_No', 'discount_Yes', 'travel_dist_2–5 km',
    'travel_dist_6–10 km', 'travel_dist_Less than 2 km',
    'travel_dist_More than 10 km', 'outing_freq_2–3 times',
    'outing_freq_4–5 times', 'outing_freq_More than 5 times',
    'outing_freq_Once or less', 'year_1st Year', 'year_2nd Year',
    'year_3rd Year', 'year_4th Year / Final Year'
]]

In [757]:
X

,allowance,group_size_2 people,group_size_3–4 people,group_size_5–7 people,group_size_8 or more,peer_influence_1,peer_influence_2,peer_influence_3,peer_influence_4,peer_influence_5,...,travel_dist_Less than 2 km,travel_dist_More than 10 km,outing_freq_2–3 times,outing_freq_4–5 times,outing_freq_More than 5 times,outing_freq_Once or less,year_1st Year,year_2nd Year,year_3rd Year,year_4th Year / Final Year
0,1500,False,True,False,False,False,False,False,True,False,...,True,False,True,False,False,False,False,True,False,False
1,12500,False,False,True,False,False,False,True,False,False,...,False,False,False,True,False,False,False,True,False,False
2,4500,False,False,True,False,False,False,True,False,False,...,False,False,True,False,False,False,False,True,False,False
3,8000,True,False,False,False,False,False,True,False,False,...,True,False,True,False,False,False,True,False,False,False
4,4500,False,True,False,False,False,False,False,True,False,...,False,False,False,False,True,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,8000,True,False,False,False,False,False,False,False,True,...,True,False,True,False,False,False,False,True,False,False
136,8000,False,False,True,False,False,False,False,True,False,...,False,False,False,False,False,True,False,True,False,False
137,4500,False,True,False,False,False,False,True,False,False,...,False,False,True,False,False,False,True,False,False,False
138,1500,False,False,True,False,False,False,True,False,False,...,False,False,False,True,False,False,False,True,False,False
139,18000,False,False,True,False,False,True,False,False,False,...,False,False,False,False,True,False,False,True,False,False

In [758]:
from sklearn.linear_model import Ridge, RidgeCV, Lasso, LassoCV
alphas = 10**np.linspace(10,-2,100)*0.5
lasso = Lasso()
coefs = []

for a in alphas:
    lasso.set_params(alpha=a)
    lasso.fit(X, Y)
    coefs.append(lasso.coef_)
    
np.shape(coefs)

/opt/miniconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.683e+06, tolerance: 6.092e+03
  model = cd_fast.enet_coordinate_descent(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.681e+06, tolerance: 6.092e+03
  model = cd_fast.enet_coordinate_descent(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.680e+06, tolerance: 6.092e+03
  model = cd_fast.enet_coordinate_descent(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.834e+07, tolerance: 6.092e+03
  model = cd_fast.enet_coordinate_descent(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.679e+06, tolerance: 6.092e+03
  model = cd_fast.enet_coordinate_descent(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.793e+07, tolerance: 6.092e+03
  model = cd_fast.enet_coordinate_descent(

(100, 57)

In [760]:
from sklearn.linear_model import RidgeCV, LassoCV
import numpy as np

alphas = np.logspace(-6, 2, 400)  # 0.001 to 1000, 100 values

# For Lasso (if you want that too)
lassocv = LassoCV(alphas=alphas, cv=5)
lassocv.fit(X, Y)
print("Best Lasso alpha:", lassocv.alpha_)

Best Lasso alpha: 37.92690190732246

In [761]:
fitR=Lasso(alpha=37.92690190732246) #alpha is lambda
fitR.fit(X,Y)
fitR.coef_
print(pd.Series(fitR.coef_, index=X.columns).map('{:.4f}'.format))

# allowance,spend_reason_My friends were spending so I did too (peer influence), travel_dist_Less than 2 km, peer_influence_3

allowance                                                                 0.0229
group_size_2 people                                                       0.0000
group_size_3–4 people                                                   -10.6637
group_size_5–7 people                                                    -0.0000
group_size_8 or more                                                      0.0000
peer_influence_1                                                         -0.0000
peer_influence_2                                                         -0.0000
peer_influence_3                                                         45.6456
peer_influence_4                                                         -0.0000
peer_influence_5                                                         -0.0000
gender_Female                                                            -0.0000
gender_Male                                                               0.0000
venue_Café / Coffee Shop                                                  0.0000
venue_Mall / Shopping                                                     0.0000
venue_Movie Theatre                                                      -0.0000
venue_Other                                                               0.0000
venue_Park / Outdoor space                                               -0.0000
venue_Pub / Bar / Lounge                                                 -0.0000
venue_Restaurant / Dhaba                                                  0.0000
day_Friday                                                               -0.0000
day_Weekday (Mon–Thu)                                                     0.0000
day_Weekend (Sat–Sun)                                                    -0.0000
intiated_plan_A friend did                                               -0.0000
intiated_plan_I did                                                      -0.0000
intiated_plan_It was a group decision                                     0.0000
intiated_plan_It was spontaneous, no one planned it                       0.0000
occasion_After exams / stress relief                                      0.0000
occasion_Celebration (birthday, farewell, etc.)                           0.0000
occasion_Date / romantic outing                                           0.0000
occasion_Just hanging out (no specific reason)                           -0.0000
occasion_Other                                                           -0.0000
exceed_budget_I spent exactly what I planned                             -0.0000
exceed_budget_No budget                                                   0.0000
exceed_budget_No, I stayed within my budget                              -0.0000
exceed_budget_Yes, I spent more than I planned                            0.0000
spend_reason_I just didn't track / wasn't paying attention               -0.0000
spend_reason_I was in a good mood                                        -0.0000
spend_reason_I was trying to save / was on a budget                      -0.0000
spend_reason_It was a special occasion so I didn't hold back             -0.0000
spend_reason_My friends were spending so I did too (peer influence)       0.0000
spend_reason_The venue/place itself was expensive                       105.3541
rough_budget_No                                                           0.0000
rough_budget_Yes                                                         -0.0000
discount_No                                                              -0.0000
discount_Yes                                                              0.0000
travel_dist_2–5 km                                                       -0.0000
travel_dist_6–10 km                                                       0.0000
travel_dist_Less than 2 km                                             -186.2703
travel_dist_More than 10 km                                               0.0000
outing_freq_2–3 times                                                    -0.0000
outing_freq_4–5 times                                                     0.0000
outing_freq_More than 5 times                                            -0.0000
outing_freq_Once or less                                                  0.0000
year_1st Year                                                             0.0000
year_2nd Year                                                           -18.3702
year_3rd Year                                                             0.0000
year_4th Year / Final Year                                                0.0000
dtype: object

In [768]:
import statsmodels.formula.api as smf

lm_fit = smf.ols('spending ~ allowance + '
                 'Q("group_size_3–4 people") + '
                 'Q("peer_influence_3") + '
                 'Q("spend_reason_The venue/place itself was expensive") + '
                 'Q("travel_dist_Less than 2 km") + '
                 'Q("year_3rd Year")',
                 data=df).fit()

print(lm_fit.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               spending   R-squared:                       0.166
Model:                            OLS   Adj. R-squared:                  0.128
Method:                 Least Squares   F-statistic:                     4.398
Date:                Wed, 22 Apr 2026   Prob (F-statistic):           0.000436
Time:                        18:46:21   Log-Likelihood:                -1094.8
No. Observations:                 140   AIC:                             2204.
Df Residuals:                     133   BIC:                             2224.
Df Model:                           6
Covariance Type:            nonrobust
==================================================================================================================================
                                                                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------------------------------
Intercept                                                        657.3848    117.914      5.575      0.000     424.156     890.614
Q("group_size_3–4 people")[T.True]                              -107.3873    107.965     -0.995      0.322    -320.939     106.164
Q("peer_influence_3")[T.True]                                    215.1517    109.930      1.957      0.052      -2.285     432.588
Q("spend_reason_The venue/place itself was expensive")[T.True]   289.9216    114.877      2.524      0.013      62.699     517.144
Q("travel_dist_Less than 2 km")[T.True]                         -369.5494    125.374     -2.948      0.004    -617.535    -121.564
Q("year_3rd Year")[T.True]                                        67.5804    182.431      0.370      0.712    -293.260     428.421
allowance                                                          0.0219      0.011      2.084      0.039       0.001       0.043
==============================================================================
Omnibus:                       21.103   Durbin-Watson:                   2.084
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               25.617
Skew:                           1.023   Prob(JB):                     2.74e-06
Kurtosis:                       3.454   Cond. No.                     2.78e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.78e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [769]:
import statsmodels.formula.api as smf

lm_fit = smf.ols('spending ~ allowance + '
                 'Q("peer_influence_3") + '
                 'Q("spend_reason_The venue/place itself was expensive") + '
                 'Q("travel_dist_Less than 2 km")' ,
                 data=df).fit()

print(lm_fit.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               spending   R-squared:                       0.159
Model:                            OLS   Adj. R-squared:                  0.134
Method:                 Least Squares   F-statistic:                     6.374
Date:                Wed, 22 Apr 2026   Prob (F-statistic):           9.94e-05
Time:                        18:46:27   Log-Likelihood:                -1095.4
No. Observations:                 140   AIC:                             2201.
Df Residuals:                     135   BIC:                             2215.
Df Model:                           4
Covariance Type:            nonrobust
==================================================================================================================================
                                                                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------------------------------
Intercept                                                        606.1187     99.827      6.072      0.000     408.691     803.546
Q("peer_influence_3")[T.True]                                    226.5949    108.023      2.098      0.038      12.960     440.230
Q("spend_reason_The venue/place itself was expensive")[T.True]   305.2759    113.514      2.689      0.008      80.780     529.772
Q("travel_dist_Less than 2 km")[T.True]                         -388.0107    123.622     -3.139      0.002    -632.496    -143.525
allowance                                                          0.0224      0.010      2.137      0.034       0.002       0.043
==============================================================================
Omnibus:                       21.251   Durbin-Watson:                   2.130
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               25.850
Skew:                           1.027   Prob(JB):                     2.44e-06
Kurtosis:                       3.459   Cond. No.                     2.12e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.12e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [770]:
from sklearn.model_selection import KFold, cross_val_score
import sklearn.linear_model as lm
import numpy as np

In [771]:
X = df[[
    'allowance',
    'peer_influence_3',
    'spend_reason_The venue/place itself was expensive',
    'travel_dist_Less than 2 km',
]]
Y = df['spending'] # single brackets, not double

model = lm.LinearRegression()
K = 100
kfold = KFold(K, random_state=0, shuffle=True)
mse_cv = cross_val_score(model, X, Y, cv=kfold, scoring='neg_mean_squared_error')
print("MSE:", np.mean(-mse_cv))

MSE: 362869.6270967111